### PR TITLE
Several improvements for main menu and settings page of the application

### PR DESCRIPTION
**Pull request by hakandundar34coding**
New menu is more similar to several other application menus. It looks simpler.

Note: **Feel free to cancel the pull request.**

New menu:
new

Old menu:
old

### CODE REVIEW

**Comment by hakandundar34coding** [comment]
I think there is no need for ```refresh time``` setting. The application has a refresh button for manual refresh. 1.5 seconds is used as update interval. This value is not very frequent and it does not cause high CPU usage on an old CPU (Intel Core i7-2630QM).

CPU usages:
For the Python application: 0-0.33%
Total (Python application+CLI application): 1% or less than 1%.

The CPU usages may be lower for more powerful CPUs and may be higher for less powerful CPUs.

**Comment by hakandundar34coding** [comment]
An alternative function for getting disk information of all disks by using a single and simple function:
(Works very fast: 0.012 seconds on i7-2630QM. This function requires JSON built-in Python module.)
```
def get_disk_info():

    # Get output of "lsblk" command for obtaining disk information.
    command_list = ["lsblk", "--bytes", "--json", "--output", "KNAME,TYPE,FSUSED,FSAVAIL,FSSIZE,FSUSE%,UUID,MOUNTPOINT"]
    lsblk_output = (subprocess.run(command_list, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)).stdout.decode().strip()

    # Get output of "/etc/fstab" file for obtaining "disk automount" information.
    with open("/etc/fstab", encoding="utf-8") as reader:
        etc_fstab_output = reader.read()

    # Convert JSON formatted text to Python dictionary.
    lsblk_output_dict = json.loads(lsblk_output)

    # Generate a more useful dictionary.
    disk_information_dict = {}

    for data in lsblk_output_dict["blockdevices"]:

        sub_dict = {}
        sub_dict["disk_name"] = data['kname']
        sub_dict["disk_type"] = data['type']
        sub_dict["disk_used"] = data['fsused']
        sub_dict["disk_free"] = data['fsavail']
        sub_dict["disk_size"] = data['fssize']
        sub_dict["disk_used_percent"] = data['fsuse%']
        sub_dict["disk_uuid"] = data['uuid']
        sub_dict["disk_mountpoint"] = data['mountpoint']

        disk_information_dict[data['kname']] = sub_dict

    # Add "disk automount" information into the dictionary.
    for disk_name in disk_information_dict:
        if disk_information_dict[disk_name]["disk_uuid"] != None:
            disk_uuid_text = "UUID=" + disk_information_dict[disk_name]["disk_uuid"] + " "
            if disk_uuid_text in etc_fstab_output:
                disk_autostart = etc_fstab_output.split(disk_uuid_text)[1].split("\n")[0].split()[-1]
            else:
                disk_autostart = None
        else:
            disk_autostart = None
        disk_information_dict[disk_name]["disk_autostart"] = disk_autostart

    return disk_information_dict
```

**Comment by fthaltun** [comment]
Thanks for your contribution.

We merged this.

**Comment by fthaltun** [comment]
> An alternative function for getting disk information of all disks by using a single and simple function: (Works very fast: 0.012 seconds on i7-2630QM. This function requires JSON built-in Python module.)
> 
> ```
> def get_disk_info():
> 
>     # Get output of "lsblk" command for obtaining disk information.
>     command_list = ["lsblk", "--bytes", "--json", "--output", "KNAME,TYPE,FSUSED,FSAVAIL,FSSIZE,FSUSE%,UUID,MOUNTPOINT"]
>     lsblk_output = (subprocess.run(command_list, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)).stdout.decode().strip()
> 
>     # Get output of "/etc/fstab" file for obtaining "disk automount" information.
>     with open("/etc/fstab", encoding="utf-8") as reader:
>         etc_fstab_output = reader.read()
> 
>     # Convert JSON formatted text to Python dictionary.
>     lsblk_output_dict = json.loads(lsblk_output)
> 
>     # Generate a more useful dictionary.
>     disk_information_dict = {}
> 
>     for data in lsblk_output_dict["blockdevices"]:
> 
>         sub_dict = {}
>         sub_dict["disk_name"] = data['kname']
>         sub_dict["disk_type"] = data['type']
>         sub_dict["disk_used"] = data['fsused']
>         sub_dict["disk_free"] = data['fsavail']
>         sub_dict["disk_size"] = data['fssize']
>         sub_dict["disk_used_percent"] = data['fsuse%']
>         sub_dict["disk_uuid"] = data['uuid']
>         sub_dict["disk_mountpoint"] = data['mountpoint']
> 
>         disk_information_dict[data['kname']] = sub_dict
> 
>     # Add "disk automount" information into the dictionary.
>     for disk_name in disk_information_dict:
>         if disk_information_dict[disk_name]["disk_uuid"] != None:
>             disk_uuid_text = "UUID=" + disk_information_dict[disk_name]["disk_uuid"] + " "
>             if disk_uuid_text in etc_fstab_output:
>                 disk_autostart = etc_fstab_output.split(disk_uuid_text)[1].split("\n")[0].split()[-1]
>             else:
>                 disk_autostart = None
>         else:
>             disk_autostart = None
>         disk_information_dict[disk_name]["disk_autostart"] = disk_autostart
> 
>     return disk_information_dict
> ```

Thanks, you can submit a pull request for this too.

**Pull request merged**
